-- MySQL Script generated by MySQL Workbench
-- Sun Dec  3 10:06:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Incidentes_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Incidentes_db` ;

-- -----------------------------------------------------
-- Schema Incidentes_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Incidentes_db` DEFAULT CHARACTER SET utf8 ;
USE `Incidentes_db` ;

-- -----------------------------------------------------
-- Table `Incidentes_db`.`Technician`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Incidentes_db`.`Technician` (
  `idTechnician` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`idTechnician`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Incidentes_db`.`Speciality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Incidentes_db`.`Speciality` (
  `idSpeciality` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`idSpeciality`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idSpeciality_UNIQUE` ON `Incidentes_db`.`Speciality` (`idSpeciality` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Incidentes_db`.`Technician_Speciality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Incidentes_db`.`Technician_Speciality` (
  `idTechnician_Speciality` INT NOT NULL AUTO_INCREMENT,
  `idTechnician` INT NULL,
  `idSpeciality` INT NULL,
  PRIMARY KEY (`idTechnician_Speciality`),
  CONSTRAINT `Technician_Speciality_idTechnician`
    FOREIGN KEY (`idTechnician`)
    REFERENCES `Incidentes_db`.`Technician` (`idTechnician`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Technician_Speciality_idSpeciality`
    FOREIGN KEY (`idSpeciality`)
    REFERENCES `Incidentes_db`.`Speciality` (`idSpeciality`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idTechnician_idx` ON `Incidentes_db`.`Technician_Speciality` (`idTechnician` ASC) VISIBLE;

CREATE INDEX `idSpeciality_idx` ON `Incidentes_db`.`Technician_Speciality` (`idSpeciality` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Incidentes_db`.`ProblemType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Incidentes_db`.`ProblemType` (
  `idProblemType` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL,
  `estimatedTime(days)` INT NULL,
  PRIMARY KEY (`idProblemType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Incidentes_db`.`Problem_Speciality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Incidentes_db`.`Problem_Speciality` (
  `idProblem_Speciality` INT NOT NULL,
  `idProblemType` INT NULL,
  `idSpeciality` INT NULL,
  PRIMARY KEY (`idProblem_Speciality`),
  CONSTRAINT `Problem_Speciality_idProblemType`
    FOREIGN KEY (`idProblemType`)
    REFERENCES `Incidentes_db`.`ProblemType` (`idProblemType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Problem_Speciality_idSpeciality`
    FOREIGN KEY (`idSpeciality`)
    REFERENCES `Incidentes_db`.`Speciality` (`idSpeciality`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idProblemType_idx` ON `Incidentes_db`.`Problem_Speciality` (`idProblemType` ASC) VISIBLE;

CREATE INDEX `idSpeciality_idx` ON `Incidentes_db`.`Problem_Speciality` (`idSpeciality` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Incidentes_db`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Incidentes_db`.`Customer` (
  `idCustomer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `businessName` VARCHAR(255) NULL,
  `CUIT` VARCHAR(20) NULL,
  PRIMARY KEY (`idCustomer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Incidentes_db`.`Incident`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Incidentes_db`.`Incident` (
  `idIncident` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL,
  `admissionDate` DATE NULL,
  `startDate` DATE NULL,
  `finishDate` DATE NULL,
  `totalTime(days)` INT NULL,
  `observations` MEDIUMTEXT NULL,
  `idTechnician` INT NULL,
  `idCustomer` INT NULL,
  PRIMARY KEY (`idIncident`),
  CONSTRAINT `Incident_idTechnician`
    FOREIGN KEY (`idTechnician`)
    REFERENCES `Incidentes_db`.`Technician` (`idTechnician`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Incident_idCustomer`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `Incidentes_db`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idTechnician_idx` ON `Incidentes_db`.`Incident` (`idTechnician` ASC) VISIBLE;

CREATE INDEX `idCustomer_idx` ON `Incidentes_db`.`Incident` (`idCustomer` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Incidentes_db`.`Service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Incidentes_db`.`Service` (
  `idService` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`idService`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Incidentes_db`.`Customer_Service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Incidentes_db`.`Customer_Service` (
  `idCustomer_Service` INT NOT NULL AUTO_INCREMENT,
  `idCustomer` INT NULL,
  `idService` INT NULL,
  PRIMARY KEY (`idCustomer_Service`),
  CONSTRAINT `Customer_Service_idCustomer`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `Incidentes_db`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Customer_Service_idService`
    FOREIGN KEY (`idService`)
    REFERENCES `Incidentes_db`.`Service` (`idService`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idCustomer_idx` ON `Incidentes_db`.`Customer_Service` (`idCustomer` ASC) VISIBLE;

CREATE INDEX `idService_idx` ON `Incidentes_db`.`Customer_Service` (`idService` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Incidentes_db`.`Incident_Detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Incidentes_db`.`Incident_Detail` (
  `idIncident_Detail` INT NOT NULL AUTO_INCREMENT,
  `idProblemType` INT NULL,
  `idService` INT NULL,
  `idIncident` INT NULL,
  PRIMARY KEY (`idIncident_Detail`),
  CONSTRAINT `Incident_Detail_idProblemType`
    FOREIGN KEY (`idProblemType`)
    REFERENCES `Incidentes_db`.`ProblemType` (`idProblemType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Incident_Detail_idService`
    FOREIGN KEY (`idService`)
    REFERENCES `Incidentes_db`.`Service` (`idService`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idIncident`
    FOREIGN KEY (`idIncident`)
    REFERENCES `Incidentes_db`.`Incident` (`idIncident`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idProblemType_idx` ON `Incidentes_db`.`Incident_Detail` (`idProblemType` ASC) VISIBLE;

CREATE INDEX `idService_idx` ON `Incidentes_db`.`Incident_Detail` (`idService` ASC) VISIBLE;

CREATE INDEX `idIncident_idx` ON `Incidentes_db`.`Incident_Detail` (`idIncident` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
